version: 2
defaults: &defaults
  docker:
    - image: ubuntu:14.04

jobs:
  build_linux:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Build for Linux
          command: |
            bash ci/setup_common_requirements.sh
            bash ci/build_linux.sh
  build_android_arm:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Setup common requirements
          command: |
            bash ci/setup_common_requirements.sh
      - run:
          name: Prepare the Android build environment
          command: |
            bash ci/setup_android.sh
      - run:
          name: Build for Android ARM
          command: |
            bash ci/build_android.sh
      - store_artifacts:
          path: android-arm/navit
  build_android_x86:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Setup common requirements
          command: |
            bash ci/setup_common_requirements.sh
      - run:
          name: Prepare the Android build environment
          command: |
            bash ci/setup_android.sh
      - run:
          name: Build for Android X86
          command: |
            bash ci/build_android_x86.sh
      - store_artifacts:
          path: android-x86/navit
  build_win32:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Build for Windows
          command: |
            bash ci/setup_common_requirements.sh
            bash ci/build_win32.sh
  build_wince:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Build for Windows CE
          command: |
            bash ci/setup_common_requirements.sh
            bash ci/build_wince.sh
  build_tomtom_minimal:
    <<: *defaults
    docker:
      - image: navit/tomtom-build-image
    steps:
      - checkout
      - run:
          name: Setup common requirements
          command: |
            bash ci/setup_common_requirements.sh
      - run:
          name: Build for Tomtom (minimal)
          command: |
            bash ci/build_tomtom_minimal.sh
      - store_artifacts:
          path: /output
  build_tomtom_plugin:
    <<: *defaults
    docker:
      - image: navit/tomtom-build-image
    steps:
      - checkout
      - run:
          name: Setup common requirements
          command: |
            bash ci/setup_common_requirements.sh
      - run:
          name: Build for Tomtom (plugin)
          command: |
            bash ci/build_tomtom_plugin.sh
      - store_artifacts:
          path: /output

workflows:
  version: 2
  build_all:
    jobs:
      - build_linux
      - build_android_arm
      - build_android_x86
      - build_win32
      - build_tomtom_minimal
      - build_tomtom_plugin
      - build_wince
